### ISSUE TITLE
Sending input parameters?

### ISSUE THREAD

**Issue by mflider** [areiks/LSXAuthSwift#1]
Hi Lukasz, thanks for this library! I'm able to use it to login to the Instapaper API, but I haven't figured out a way to send input parameters to API calls. For example, I'm trying to access the "/api/1/bookmarks/list" endpoint, and send in "limit: 500" as the input parameters. I'm using your example code and calling:

```
            let authorizationHeader = LSXAuthSwift.generateAuthorizationHeader(url: InstapaperDataSource.listBookmarksURL)
            let headers = [
                "Authorization" : authorizationHeader,
                "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
                "Accept":"application/json"
            ]

            let params: [String: Any] = ["limit": 500]

            Alamofire.request(InstapaperDataSource.listBookmarksURL, method: .post, parameters: params, headers: headers).responseJSON(completionHandler: { (response) in
```

but the Instapaper server always gives me a 403 http code. If I set "params" to just be empty ("[:]"), it returns the first 25 results as expected. Have you gotten this to work in your own apps?

Thanks again for the library!

**Comment by areiks** [comment]
Hello @mflider,

You need to build the authorization header with the input parameters (thats the tricky part with XAuth - input parameters need also to be encrypted). So your code would look like this:

        
```
        let parameters = [
            "limit":String(500)
        ]
        
        let authorizationHeader = XAuthSwift.generateAuthorizationHeader(url: InstapaperEndpoint.ListBookmarks.path, params: parameters)
        
        let headers = [
            "Authorization":authorizationHeader,
            "Content-Type":"application/x-www-form-urlencoded; charset=utf-8",
            "Accept":"application/json"
        ]
        
        Alamofire.request(InstapaperEndpoint.ListBookmarks.path, method: .post, parameters: parameters, encoding: URLEncoding.default, headers: headers).responseJSON(completionHandler
```


I will update the example project. Let me know if it works for you!

**Comment by mflider** [comment]
Great, that worked perfectly. Thank you so much again for this library!
